abbr -a b bundle
abbr -a be 'bundle exec'
abbr -a bo 'bundle open'
abbr -a dc docker-compose
abbr -a dm 'bin/rails db:migrate'
abbr -a dr 'bin/rails db:rollback'
abbr -a ga 'git add'
abbr -a gap 'git add -p'
abbr -a gb 'git branch'
abbr -a gc 'git commit -v'
abbr -a gc! 'git commit -v --amend'
abbr -a gco 'git checkout'
abbr -a gcp 'git cherry-pick'
abbr -a gd 'git diff'
abbr -a gds 'git diff --staged'
abbr -a gf 'git fetch'
abbr -a gl 'git pull'
abbr -a gg 'git log'
abbr -a gp 'git push -u'
abbr -a gpf 'git push --force-with-lease'
abbr -a grs 'git reset'
abbr -a gsh 'git show'
abbr -a gss 'git stash'
abbr -a gst 'git status'
abbr -a ll 'ls -alFh'
abbr -a nv nvim
abbr -a r 'git rebase'
abbr -a ra 'git rebase --abort'
abbr -a rc 'git rebase --continue'
abbr -a rim 'git rebase -i origin/main'
abbr -a sc 'bin/rails console'
abbr -a ss 'bin/rails server'
abbr -a t 'tmux'
abbr -a tkr 'tmux kill-server'
abbr -a ts tmux-sessionizer
abbr -a y yarn
