abbr -a be 'bundle exec'
abbr -a ga 'git add'
abbr -a gap 'git add -p'
abbr -a gb 'git branch'
abbr -a gc 'git commit -v'
abbr -a gc! 'git commit -v --amend'
abbr -a gco 'git checkout'
abbr -a gcob 'git checkout -b'
abbr -a gd 'git diff'
abbr -a gf 'git fetch'
abbr -a gfrb 'git fetch && git rebase origin/master'
abbr -a gl 'git pull'
abbr -a gp 'git push -u'
abbr -a gpf 'git push --force-with-lease'
abbr -a grbc 'git rebase --continue'
abbr -a gst 'git status'
abbr -a sc 'bin/rails console'
abbr -a ss 'bin/rails server'
abbr -a y yarn
