abbr -a -U -- b bundle
abbr -a -U -- be 'bundle exec'
abbr -a -U -- dc docker-compose
abbr -a -U -- ga 'git add'
abbr -a -U -- gap 'git add -p'
abbr -a -U -- gb 'git branch'
abbr -a -U -- gc 'git commit -v'
abbr -a -U -- gc! 'git commit -v --amend'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gcob 'git checkout -b'
abbr -a -U -- gd 'git diff'
abbr -a -U -- gf 'git fetch'
abbr -a -U -- gfrb 'git fetch && git rebase origin/master'
abbr -a -U -- gl 'git pull'
abbr -a -U -- gp 'git push -u'
abbr -a -U -- gpf 'git push --force-with-lease'
abbr -a -U -- grbc 'git rebase --continue'
abbr -a -U -- gst 'git status'
abbr -a -U -- ll 'ls -alFh'
abbr -a -U -- sc 'bin/rails console'
abbr -a -U -- ss 'bin/rails server'
abbr -a -U -- y yarn
