abbr -a -U -- b bundle
abbr -a -U -- be 'bundle exec'
abbr -a -U -- bo 'bundle open'
abbr -a -U -- dc docker-compose
abbr -a -U -- dm 'bin/rails db:migrate'
abbr -a -U -- dr 'bin/rails db:rollback'
abbr -a -U -- ga 'git add'
abbr -a -U -- gap 'git add -p'
abbr -a -U -- gb 'git branch'
abbr -a -U -- gc 'git commit -v'
abbr -a -U -- gc! 'git commit -v --amend'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gcp 'git cherry-pick'
abbr -a -U -- gd 'git diff'
abbr -a -U -- gds 'git diff --staged'
abbr -a -U -- gf 'git fetch'
abbr -a -U -- gl 'git pull'
abbr -a -U -- gg 'git log'
abbr -a -U -- gp 'git push -u'
abbr -a -U -- gpf 'git push --force-with-lease'
abbr -a -U -- grs 'git reset'
abbr -a -U -- gsh 'git show'
abbr -a -U -- gss 'git stash'
abbr -a -U -- gst 'git status'
abbr -a -U -- ll 'ls -alFh'
abbr -a -U -- nv nvim
abbr -a -U -- r 'git rebase'
abbr -a -U -- ra 'git rebase --abort'
abbr -a -U -- rc 'git rebase --continue'
abbr -a -U -- rim 'git rebase -i origin/main'
abbr -a -U -- sc 'bin/rails console'
abbr -a -U -- ss 'bin/rails server'
abbr -a -U -- ts tmux-sessionizer
abbr -a -U -- y yarn
