brew "awscli"
brew "coreutils"
brew "ctags"
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "neovim", args: ["HEAD"]
brew "par"
brew "postgresql"
brew "python3"
brew "redis"
brew "the_silver_searcher"
brew "tmux"

cask "alacritty"
cask "1password"
cask "authy"
cask "cold-turkey-blocker"
cask "google-chrome"
cask "insomnia"
cask "krisp"
cask "slack"
cask "tuple"
cask "whatsapp"
cask "zoom"
